#!/bin/bash

. "/usr/bin/variables"

# unmount fuses
fusermount -uz "${cloud_encrypt_dir}"
fusermount -uz "${cloud_decrypt_dir}"
fusermount -uz "${local_decrypt_dir}"
fusermount -uz "${local_media_dir}"